### ISSUE TITLE
File should not execute when imported

### ISSUE THREAD

**Issue by Qwendu** [plaf2000/ethz-video-lister#1]
Add
``
if __name__ = "__main__":
``
to avoid the python file to be executed when imported in a different file.
Then one could use this handy utility to automate more complex things.

For more info see this StackOverflow post:
https://stackoverflow.com/questions/419163/what-does-if-name-main-do

**Comment by plaf2000** [comment]
> Add `if __name__ = "__main__":` to avoid the python file to be executed when imported in a different file. Then one could use this handy utility to automate more complex things.
> 
> For more info see this StackOverflow post: https://stackoverflow.com/questions/419163/what-does-if-name-main-do

Good point, thank you! I changed the code structure. I put most of the things inside a new `Videos` class, so that it could be used in other projects, and modified the remaining code as you suggested. Please let me know if there's any issue with that.
